#!/usr/bin/env python3
"""Create or verify the repository's tracked-file SHA-256 manifest.

The manifest deliberately excludes itself and generated/ignored build artifacts.
It can therefore be verified in a Git checkout, a Git archive, or an extracted ZIP.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import stat
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "MANIFEST.sha256"
DIGEST_RE = re.compile(r"^[0-9a-f]{64}$")

IGNORED_DIRECTORIES = {
    ".git",
    ".venv",
    ".awg-state",
    "__pycache__",
    "build",
    "dist",
    "dist-release",
    "htmlcov",
    "release",
}
IGNORED_SUFFIXES = {".pyc", ".pyo"}
IGNORED_NAMES = {".coverage", ".DS_Store", "Thumbs.db", "MANIFEST.sha256"}


def _ignored(relative: Path) -> bool:
    if relative.name in IGNORED_NAMES or relative.suffix in IGNORED_SUFFIXES:
        return True
    if any(part in IGNORED_DIRECTORIES or part.endswith(".egg-info") for part in relative.parts):
        return True
    return False


def _repository_files() -> list[Path]:
    files: list[Path] = []
    for path in ROOT.rglob("*"):
        relative = path.relative_to(ROOT)
        if _ignored(relative):
            continue
        try:
            info = path.lstat()
        except FileNotFoundError:
            raise RuntimeError(f"repository entry changed while scanning: {relative}")
        if stat.S_ISLNK(info.st_mode):
            raise RuntimeError(f"repository manifest does not permit symlinks: {relative}")
        if stat.S_ISREG(info.st_mode):
            files.append(relative)
    return sorted(files, key=lambda item: item.as_posix())


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def _parse_manifest() -> dict[str, str]:
    try:
        lines = MANIFEST.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError as exc:
        raise RuntimeError(f"manifest is missing: {MANIFEST}") from exc

    records: dict[str, str] = {}
    for line_number, line in enumerate(lines, start=1):
        if not line or line.startswith("#"):
            continue
        try:
            digest, relative_text = line.split("  ", 1)
        except ValueError as exc:
            raise RuntimeError(
                f"invalid manifest line {line_number}: expected '<sha256>  <path>'"
            ) from exc
        if not DIGEST_RE.fullmatch(digest):
            raise RuntimeError(f"invalid SHA-256 on manifest line {line_number}")
        relative = Path(relative_text)
        if (
            not relative_text
            or relative.is_absolute()
            or "\\" in relative_text
            or any(part in {"", ".", ".."} for part in relative.parts)
        ):
            raise RuntimeError(f"unsafe manifest path on line {line_number}: {relative_text!r}")
        normalized = relative.as_posix()
        if normalized in records:
            raise RuntimeError(f"duplicate manifest path: {normalized}")
        records[normalized] = digest
    return records


def write_manifest() -> None:
    records = [
        f"{_sha256(ROOT / relative)}  {relative.as_posix()}"
        for relative in _repository_files()
    ]
    payload = "\n".join(
        [
            "# Agent Workspace Guard repository SHA-256 manifest",
            "# Generated by scripts/verify_manifest.py; excludes MANIFEST.sha256 and generated artifacts.",
            *records,
            "",
        ]
    )
    MANIFEST.write_text(payload, encoding="utf-8", newline="\n")
    print(f"Manifest written: {len(records)} files")


def verify_manifest() -> None:
    expected = _parse_manifest()
    actual_files = {path.as_posix() for path in _repository_files()}
    expected_files = set(expected)

    missing_from_manifest = sorted(actual_files - expected_files)
    missing_from_tree = sorted(expected_files - actual_files)
    errors: list[str] = []
    if missing_from_manifest:
        errors.append(
            "files omitted from manifest: " + ", ".join(missing_from_manifest)
        )
    if missing_from_tree:
        errors.append("manifest files missing from tree: " + ", ".join(missing_from_tree))

    for relative_text in sorted(expected_files & actual_files):
        actual_digest = _sha256(ROOT / relative_text)
        if actual_digest != expected[relative_text]:
            errors.append(
                f"digest mismatch for {relative_text}: expected {expected[relative_text]}, got {actual_digest}"
            )

    if errors:
        raise RuntimeError("repository manifest verification failed:\n- " + "\n- ".join(errors))
    print(f"Manifest verified: {len(expected)} files")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate MANIFEST.sha256 from the current repository tree",
    )
    args = parser.parse_args(argv)
    try:
        if args.write:
            write_manifest()
        else:
            verify_manifest()
        return 0
    except (OSError, RuntimeError) as exc:
        print(f"manifest error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
